### ISSUE TITLE
设置事件没效果

### ISSUE THREAD

**Issue by zhaoxiuyu** [7heaven/SHSwitchView#10]
ShSwitchView 设置 setOnClickListener 没有效果

**Comment by 7heaven** [comment]
OnClickListener相关的事件处理被覆盖了，请使用setOnSwitchStateChangeListener

**Comment by zhaoxiuyu** [comment]
@7heaven   使用 这个 setOnSwitchStateChangeListener ，当我设置setOn(true)的时候 回调事件也会执行，这不是我所期望的。
